---
title: "GlmsAnalysis, Valcarcel-Gebauer et al."
output: html_document
date: 10/03/2026
---

```{r setup, include=FALSE}
# MuMIn: For model selection based on Akaike Criterion (AIC)
if (!require("MuMIn")) install.packages("MuMIn")
# car for collinearity
if (!require("car")) install.packages("car")
# formatting nas
if (!require("dplyr")) install.packages("dplyr")
# colinearity with checkcolinearity
if (!require("performance")) install.packages("performance")
# summary with j.tools
if (!require("jtools")) install.packages("jtools")
# for post-hocs
if (!require("emmeans")) install.packages("emmeans")

# Package loading
library(MuMIn)
library(car)
library(dplyr)
library(performance) # checkcollinearity
library(jtools) #summ
library(emmeans) #post-hocs
```

## Loading data
```{r}
library(readxl)
Data1 <- read_excel("")
View(Data1)
```

## PHYSICAL Aggression 
            and EAE
```{r}
# Converting Physical Aggression to z-scores
z.PhysicalAggression <- as.vector(scale(Data1$PhysicalAggression))

# Full model
fullPHY <- glm(z.PhysicalAggression ~ Origin + EarlyRearing + AgeArrival + PastExperiences + MotherSeparation + Abuse, data = Data1, na.action = "na.fail")
AICc(fullPHY)
check_collinearity(fullPHY)

# Best model
bestPHY <- dredge(fullPHY,  rank = "AICc", trace=4, fixed = NULL, m.lim = NULL)
subset(bestPHY, delta <= 4)
model.avg(bestPHY, subset = cumsum(weight) <= .95)
summary(get.models(bestPHY, 1)[[1]]) 

BestmodelPHY <- (get.models(bestPHY, 1)[[1]])
AICc(BestmodelPHY) 

# VIFS:
check_collinearity(BestmodelPHY) 

# POST-HOCS:
emmeans (BestmodelPHY, pairwise ~ EarlyRearing) 
```


## DISRUPTIVE Behavior
            and EAE
```{r}
# Converting Disruptive Behavior to z-scores
z.DisruptiveBehavior <- as.vector(scale(Data1$DisruptiveBehavior))

# Full model
fulldis <- glm(z.DisruptiveBehavior ~ Origin + EarlyRearing + AgeArrival + PastExperiences + MotherSeparation + Abuse, data = Data1, na.action = "na.fail")
AICc(fulldis) 
check_collinearity(fulldis) 

# Best model
bestdis <- dredge(fulldis,  rank = "AICc", trace=4, fixed = NULL, m.lim = NULL)
subset(bestdis, delta <= 4)
model.avg(bestdis, subset = cumsum(weight) <= .95)
summary(get.models(bestdis, 1)[[1]]) 

Bestmodeldis <- (get.models(bestdis, 1)[[1]])
AICc(Bestmodeldis) 

# VIFS: No need

# POST-HOCS:
emmeans (Bestmodeldis, pairwise ~ EarlyRearing)
```


# Plots - Visualization Data: Influence of EAE on STAB-Q-Chimp subtypes

```{r}
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("ggpubr")) install.packages("ggpubr")
library(ggplot2)
library(ggpubr)

library(multcomp)
library(ggsignif)
```

# Best model - Physical Aggression and Early Rearing
```{r}
colors1 = c("#C1CDCD", "#EE3B3B", "#8EE5EE", "#BCEE68")
plot.new() #Crear gráfico en planco
set.seed(1)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#FDFAFA")
par(mfrow = c(1,2))

# Best model: PHY - Early Rearing
dev.new(width = 10, height = 10)
boxplot(z.PhysicalAggression ~ EarlyRearing, data=Data1, horizontal = FALSE,
        lwd = 1,
        col = colors1,
        xlab = "Early Rearing Conditions",
        ylab = "Physical aggression",
        border = "black",
        outpch = 25,
        outbg = "black",
        whiskcol = "black",
        whisklty = 1,
        lty = 1,
        names = c("Mother-reared", "Hand-reared"))
```


# Best model - Disruptive Behavior and Early Rearing
```{r}
colors1 = c("#C1CDCD", "#EE3B3B", "#8EE5EE", "#BCEE68")
plot.new() #Crear gráfico en planco
set.seed(1)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#FDFAFA")
par(mfrow = c(1,2))

# Best model 2: DB - Early Rearing
dev.new(width = 10, height = 6)
boxplot(z.DisruptiveBehavior ~ Origin, data=Data1, horizontal = FALSE,
        lwd = 1,
        col = colors1,
        xlab = "Early Rearing Conditions",
        ylab = "Disruptive Behavior",
        border = "black",
        outpch = 25,
        outbg = "black",
        whiskcol = "black",
        whisklty = 1,
        lty = 1,
        names = c("Mother-reared", "Hand-reared"))
```
